situation_center/ai/urls.py
from django.urls import path

from . import views


app_name = 'ai'

urlpatterns = [
    # Атомка
    path('atom/', views.atom, name='atom'),
    path('atom/<slug:slug>/', views.atom_view, name='atom_view'),
    # Здравоохранение
    path('hospital/', views.hospital, name='hospital'),
    path('hospital/<slug:slug>/', views.hospital_view, name='hospital_view'),
    # Образование
    path('study/', views.study, name='study'),
    path('study/<slug:slug>/', views.study_view, name='study_view'),
    # Демография
    path('demographics/', views.demographics, name='demographics'),
    path('demographics/<slug:slug>/', views.demographics_view, name='demographics_view'),
    # Культура
    path('culture/', views.culture, name='culture'),
    path('culture/<slug:slug>/', views.culture_view, name='culture_view'),
    # Дороги
    path('road/', views.road, name='road'),
    path('road/<slug:slug>/', views.road_view, name='road_view'),
    # Наука
    path('science/', views.science, name='science'),
    path('science/<slug:slug>/', views.science_view, name='science_view'),
    # Экология
    path('ecology/', views.ecology, name='ecology'),
    path('ecology/<slug:slug>/', views.ecology_view, name='ecology_view'),
    # Предпринимательство
    path('business/', views.business, name='business'),
    path('business/<slug:slug>/', views.business_view, name='business_view'),
    # Туризм
    path('turism/', views.turism, name='turism'),
    path('turism/<slug:slug>/', views.turism_view, name='turism_view'),
    # Жилье
    path('house/', views.house, name='house'),
    path('house/<slug:slug>/', views.house_view, name='house_view'),
    # Международная кооперация и экспорт
    path('world/', views.world, name='world'),
    path('world/<slug:slug>/', views.world_view, name='world_view'),
    # Труд
    path('labour/', views.labour, name='labour'),
    path('labour/<slug:slug>/', views.labour_view, name='labour_view'),
    # Экономика
    path('econom/', views.econom, name='econom'),
    path('econom/<slug:slug>/', views.econom_view, name='econom_view'),
    # Расширение магистральной инфраструктуры
    path('mainline/', views.mainline, name='mainline'),
    path('mainline/<slug:slug>/', views.mainline_view, name='mainline_view'),
    # Промышленность
    path('industry/', views.industry, name='industry'),
    path('industry/<slug:slug>/', views.industry_view, name='industry_view'),
    # Сельское хозяйство
    path('agro/', views.agro, name='agro'),
    path('agro/<slug:slug>/', views.agro_view, name='agro_view'),
    # Строительство
    path('building/', views.building, name='building'),
    path('building/<slug:slug>/', views.building_view, name='building_view'),
    # Транспорт
    path('transport/', views.transport, name='transport'),
    path('transport/<slug:slug>/', views.transport_view, name='transport_view'),
    # Торговля
    path('trading/', views.trading, name='trading'),
    path('trading/<slug:slug>/', views.trading_view, name='trading_view'),
    # Услуги
    path('uslugi/', views.uslugi, name='uslugi'),
    path('uslugi/<slug:slug>/', views.uslugi_view, name='uslugi_view'),
    # Инвестиции
    path('investing/', views.investing, name='investing'),
    path('investing/<slug:slug>/', views.investing_view, name='investing_view'),
    # Финансы предприятий
    path('finpr/', views.finpr, name='finpr'),
    path('finpr/<slug:slug>/', views.finpr_view, name='finpr_view'),
    # Потребительские цены
    path('price/', views.price, name='price'),
    path('price/<slug:slug>/', views.price_view, name='price_view'),
    # Цены производителей
    path('prodprice/', views.prodprice, name='prodprice'),
    path('prodprice/<slug:slug>/', views.prodprice_view, name='prodprice_view'),
    # Доходы
    path('revenue/', views.revenue, name='revenue'),
    path('revenue/<slug:slug>/', views.revenue_view, name='revenue_view'),
    # Зарплата
    path('salary/', views.salary, name='salary'),
    path('salary/<slug:slug>/', views.salary_view, name='salary_view'),
    # Безработица
    path('joblessness/', views.joblessness, name='joblessness'),
    path('joblessness/<slug:slug>/', views.joblessness_view, name='joblessness_view'),
    # Рынок труда
    path('jobmarket/', views.jobmarket, name='jobmarket'),
    path('jobmarket/<slug:slug>/', views.jobmarket_view, name='jobmarket_view'),
    # Малые и средние предприятия
    path('smcompany/', views.smcompany, name='smcompany'),
    path('smcompany/<slug:slug>/', views.smcompany_view, name='smcompany_view'),
    # Население
    path('population/', views.population, name='population'),
    path('population/<slug:slug>/', views.population_view, name='population_view'),
    # Уровень жизни населения
    path('levelhealth/', views.levelhealth, name='levelhealth'),
    path('levelhealth/<slug:slug>/', views.levelhealth_view, name='levelhealth_view'),
    # Охрана природы
    path('securenature/', views.securenature, name='securenature'),
    path('securenature/<slug:slug>/', views.securenature_view, name='securenature_view'),
    # Основные фонды
    path('capitalassets/', views.capitalassets, name='capitalassets'),
    path('capitalassets/<slug:slug>/', views.capitalassets_view, name='capitalassets_view'),
    # Предприятия и организации
    path('organization/', views.organization, name='organization'),
    path('organization/<slug:slug>/', views.organization_view, name='organization_view'),
    # С/х, лесное, рыболовство, рыбоводство
    path('shlrr/', views.shlrr, name='shlrr'),
    path('shlrr/<slug:slug>/', views.shlrr_view, name='shlrr_view'),
    # Информационные и коммуникационные технологии
    path('infotechnology/', views.infotechnology, name='infotechnology'),
    path('infotechnology/<slug:slug>/', views.infotechnology_view, name='infotechnology_view'),
    # Финансы
    path('finance/', views.finance, name='finance'),
    path('finance/<slug:slug>/', views.finance_view, name='finance_view'),
    # Внешняя торговля
    path('foreigntrading/', views.foreigntrading, name='foreigntrading'),
    path('foreigntrading/<slug:slug>/', views.foreigntrading_view, name='foreigntrading_view'),
    # Валовой региональный продукт
    path('vrp/', views.vrp, name='vrp'),
    path('vrp/<slug:slug>/', views.vrp_view, name='vrp_view'),
    # Промышленное производство
    path('industrialprod/', views.industrialprod, name='industrialprod'),
    path('industrialprod/<slug:slug>/', views.industrialprod_view, name='industrialprod_view'),

    # Модель
    path('download_model/<str:filename>/', views.download_model, name='download_model'),
]

situation_center/nathprojects/urls.py
from django.urls import path

from . import views


app_name = 'nathprojects'

urlpatterns = [
    # Здравоохранение
    path('project-hospital/', views.hospital, name='hospital'),
    path('project-hospital/<slug:slug>/', views.hospital_detail, name='hospital_detail'),
    # Образование
    path('project-study/', views.study, name='study'),
    path('project-study/<slug:slug>/', views.study_detail, name='study_detail'),
    # Демография
    path('project-demographics/', views.demographics, name='demographics'),
    path('project-demographics/<slug:slug>/', views.demographics_detail, name='demographics_detail'),
    # Культура
    path('project-culture/', views.culture, name='culture'),
    path('project-culture/<slug:slug>/', views.culture_detail, name='culture_detail'),
    # Дороги
    path('project-road/', views.road, name='road'),
    path('project-road/<slug:slug>/', views.road_detail, name='road_detail'),
    # Наука
    path('project-science/', views.science, name='science'),
    path('project-science/<slug:slug>/', views.science_detail, name='science_detail'),
    # Экология
    path('project-ecology/', views.ecology, name='ecology'),
    path('project-ecology/<slug:slug>/', views.ecology_detail, name='ecology_detail'),
    # Предпринимательство
    path('project-business/', views.business, name='business'),
    path('project-business/<slug:slug>/', views.business_detail, name='business_detail'),
    # Туризм
    path('project-turism/', views.turism, name='turism'),
    path('project-turism/<slug:slug>/', views.turism_detail, name='turism_detail'),
    # Жилье
    path('project-house/', views.house, name='house'),
    path('project-house/<slug:slug>/', views.house_detail, name='house_detail'),
    # Международка
    path('project-world/', views.world, name='world'),
    path('project-world/<slug:slug>/', views.world_detail, name='world_detail'),
    # Труд
    path('project-labour/', views.labour, name='labour'),
    path('project-labour/<slug:slug>/', views.labour_detail, name='labour_detail'),
    # Атомка
    path('project-atom/', views.atom, name='atom'),
    path('project-atom/<slug:slug>/', views.atom_detail, name='atom_detail'),
    # Экономика
    path('project-econom/', views.econom, name='econom'),
    path('project-econom/<slug:slug>/', views.econom_detail, name='econom_detail'),
    # Магистральная
    path('project-mainline/', views.mainline, name='mainline'),
    path('project-mainline/<slug:slug>/', views.mainline_detail, name='mainline_detail'),
]

situation_center/situation_center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from news.sitemaps import NewsSitemap

from django.conf import settings


handler400 = 'errors.views.tr_handler400'
handler403 = 'errors.views.tr_handler403'
handler404 = 'errors.views.tr_handler404'
handler429 = 'errors.views.tr_handler429'
handler500 = 'errors.views.tr_handler500'
handler503 = 'errors.views.tr_handler503'

sitemaps = {
    'posts': NewsSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('news.urls', namespace='news')),
    path('projects/', include('nathprojects.urls', namespace='nathprojects')),
    path('', include('errors.urls', namespace='errors')),
    path('', include('strategy.urls', namespace='strategy')),
    path('', include('userauth.urls', namespace='userauth')),
    path('api/', include('api.urls', namespace='api')),
    path('operdata/', include('operdata.urls', namespace='operdata')),
    path('yeardata/', include('yeardata.urls', namespace='yeardata')),
    path('rosstat/', include('rosstat.urls', namespace='rosstat')),
    path('foresttrees/', include('foresttrees.urls', namespace='foresttrees')),
    path('activeforecast/', include('activeforecast.urls', namespace='activeforecast')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('clustering/', include('clustering.urls', namespace='clustering')),

    # Карта сайта
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

situation_center/templates/nathprojects/atom.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">НАЦИОНАЛЬНЫЙ ПРОЕКТ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Развитие технологий в области атомной энергии</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере атомной энергии. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты развития
            технологий в области атомной энергии, такие как динамика использования атомной энергии,
            распределение типов ядерных реакторов, эффективность мер по обеспечению безопасности
            ядерных установок и многое другое. Они помогают анализировать и понимать текущее
            состояние сферы атомной энергетики в различных регионах или странах, а также
            выявлять тенденции и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели атомной энергии, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели атомной энергии
            на одной панели управления. Они облегчают мониторинг текущей ситуации в атомной энергии,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for atom in atoms %}
            <div class="hospital-section__card">
                <a href="{% url 'nathprojects:atom_detail' slug=atom.slug %}" class="hospital-section__link">{{ atom.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/atom_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ atom.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'nathprojects:atom_detail' slug=atom.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ atom.description }}</p>
            </div>

            
            {% comment %} <div>
                <h2>Круговая диаграмма</h2>
                <div>{{ pie_chart|safe }}</div>
            </div> {% endcomment %}
            <!-- Второй график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img2.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
            <!-- Третий график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img3.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/business.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">НАЦИОНАЛЬНЫЙ ПРОЕКТ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Предпринимательство</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере предпринимательства. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты
            предпринимательства, такие как динамика создания новых предприятий, распределение
            видов бизнеса по отраслям, эффективность инвестиций и многое другое. Они помогают
            анализировать и понимать текущее состояние предпринимательской активности в
            различных регионах или странах, а также выявлять тенденции и прогнозировать
            возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели предпринимательства, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели предпринимательства
            на одной панели управления. Они облегчают мониторинг текущей ситуации в предпринимательства,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for business in businesses %}
            <div class="hospital-section__card">
                <a href="{% url 'nathprojects:business_detail' slug=business.slug %}" class="hospital-section__link">{{ business.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/culture_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ culture.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'nathprojects:culture_detail' slug=culture.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ culture.description }}</p>
            </div>


        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/demographics.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">НАЦИОНАЛЬНЫЙ ПРОЕКТ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Демография</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере демографии. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты демографии,
            такие как динамика рождаемости и смертности, распределение населения по возрастным группам,
            миграционные потоки и многое другое. Они помогают анализировать и понимать текущее
            демографическое состояние в различных регионах или странах, а также выявлять тенденции
            и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели демографии, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы, влияющие на количество населения и т.д.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели демографии
            на одной панели управления. Они облегчают мониторинг текущей ситуации в демографии,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for demographics in demographicses %}
            <div class="hospital-section__card">
                <a href="{% url 'nathprojects:demographics_detail' slug=demographics.slug %}" class="hospital-section__link">{{ demographics.title }}</a>
            </div>
            {% endfor %}


        </div>
        

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/ecology_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ ecology.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'nathprojects:ecology_detail' slug=ecology.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ ecology.description }}</p>
            </div>

            
            {% comment %} <div>
                <h2>Круговая диаграмма</h2>
                <div>{{ pie_chart|safe }}</div>
            </div> {% endcomment %}
            <!-- Второй график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img2.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
            <!-- Третий график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img3.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/nathprojects/econom.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">НАЦИОНАЛЬНЫЙ ПРОЕКТ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Цифровая экономика РФ</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере цифровой экономики. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты
            цифровой экономики Российской Федерации, такие как динамика использования
            цифровых технологий, распределение цифровых услуг по отраслям, эффективность
            цифровизации экономики и многое другое. Они помогают анализировать и понимать
            текущее состояние цифровой сферы в России, а также выявлять тенденции и
            прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели цифровой экономики, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы, влияющие на здоровье населения.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели цифровой экономики
            на одной панели управления. Они облегчают мониторинг текущей ситуации в цифровой экономики,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for econom in economs %}
            <div class="hospital-section__card">
                <a href="{% url 'nathprojects:econom_detail' slug=econom.slug %}" class="hospital-section__link">{{ econom.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}