situation_center/ai/urls.py
from django.urls import path

from . import views


app_name = 'ai'

urlpatterns = [
    # Атомка
    path('atom/', views.atom, name='atom'),
    path('atom/<slug:slug>/', views.atom_view, name='atom_view'),
    # Здравоохранение
    path('hospital/', views.hospital, name='hospital'),
    path('hospital/<slug:slug>/', views.hospital_view, name='hospital_view'),
    # Образование
    path('study/', views.study, name='study'),
    path('study/<slug:slug>/', views.study_view, name='study_view'),
    # Демография
    path('demographics/', views.demographics, name='demographics'),
    path('demographics/<slug:slug>/', views.demographics_view, name='demographics_view'),
    # Культура
    path('culture/', views.culture, name='culture'),
    path('culture/<slug:slug>/', views.culture_view, name='culture_view'),
    # Дороги
    path('road/', views.road, name='road'),
    path('road/<slug:slug>/', views.road_view, name='road_view'),
    # Наука
    path('science/', views.science, name='science'),
    path('science/<slug:slug>/', views.science_view, name='science_view'),
    # Экология
    path('ecology/', views.ecology, name='ecology'),
    path('ecology/<slug:slug>/', views.ecology_view, name='ecology_view'),
    # Предпринимательство
    path('business/', views.business, name='business'),
    path('business/<slug:slug>/', views.business_view, name='business_view'),
    # Туризм
    path('turism/', views.turism, name='turism'),
    path('turism/<slug:slug>/', views.turism_view, name='turism_view'),
    # Жилье
    path('house/', views.house, name='house'),
    path('house/<slug:slug>/', views.house_view, name='house_view'),
    # Международная кооперация и экспорт
    path('world/', views.world, name='world'),
    path('world/<slug:slug>/', views.world_view, name='world_view'),
    # Труд
    path('labour/', views.labour, name='labour'),
    path('labour/<slug:slug>/', views.labour_view, name='labour_view'),
    # Экономика
    path('econom/', views.econom, name='econom'),
    path('econom/<slug:slug>/', views.econom_view, name='econom_view'),
    # Расширение магистральной инфраструктуры
    path('mainline/', views.mainline, name='mainline'),
    path('mainline/<slug:slug>/', views.mainline_view, name='mainline_view'),
    # Промышленность
    path('industry/', views.industry, name='industry'),
    path('industry/<slug:slug>/', views.industry_view, name='industry_view'),
    # Сельское хозяйство
    path('agro/', views.agro, name='agro'),
    path('agro/<slug:slug>/', views.agro_view, name='agro_view'),
    # Строительство
    path('building/', views.building, name='building'),
    path('building/<slug:slug>/', views.building_view, name='building_view'),
    # Транспорт
    path('transport/', views.transport, name='transport'),
    path('transport/<slug:slug>/', views.transport_view, name='transport_view'),
    # Торговля
    path('trading/', views.trading, name='trading'),
    path('trading/<slug:slug>/', views.trading_view, name='trading_view'),
    # Услуги
    path('uslugi/', views.uslugi, name='uslugi'),
    path('uslugi/<slug:slug>/', views.uslugi_view, name='uslugi_view'),
    # Инвестиции
    path('investing/', views.investing, name='investing'),
    path('investing/<slug:slug>/', views.investing_view, name='investing_view'),
    # Финансы предприятий
    path('finpr/', views.finpr, name='finpr'),
    path('finpr/<slug:slug>/', views.finpr_view, name='finpr_view'),
    # Потребительские цены
    path('price/', views.price, name='price'),
    path('price/<slug:slug>/', views.price_view, name='price_view'),
    # Цены производителей
    path('prodprice/', views.prodprice, name='prodprice'),
    path('prodprice/<slug:slug>/', views.prodprice_view, name='prodprice_view'),
    # Доходы
    path('revenue/', views.revenue, name='revenue'),
    path('revenue/<slug:slug>/', views.revenue_view, name='revenue_view'),
    # Зарплата
    path('salary/', views.salary, name='salary'),
    path('salary/<slug:slug>/', views.salary_view, name='salary_view'),
    # Безработица
    path('joblessness/', views.joblessness, name='joblessness'),
    path('joblessness/<slug:slug>/', views.joblessness_view, name='joblessness_view'),
    # Рынок труда
    path('jobmarket/', views.jobmarket, name='jobmarket'),
    path('jobmarket/<slug:slug>/', views.jobmarket_view, name='jobmarket_view'),
    # Малые и средние предприятия
    path('smcompany/', views.smcompany, name='smcompany'),
    path('smcompany/<slug:slug>/', views.smcompany_view, name='smcompany_view'),
    # Население
    path('population/', views.population, name='population'),
    path('population/<slug:slug>/', views.population_view, name='population_view'),
    # Уровень жизни населения
    path('levelhealth/', views.levelhealth, name='levelhealth'),
    path('levelhealth/<slug:slug>/', views.levelhealth_view, name='levelhealth_view'),
    # Охрана природы
    path('securenature/', views.securenature, name='securenature'),
    path('securenature/<slug:slug>/', views.securenature_view, name='securenature_view'),
    # Основные фонды
    path('capitalassets/', views.capitalassets, name='capitalassets'),
    path('capitalassets/<slug:slug>/', views.capitalassets_view, name='capitalassets_view'),
    # Предприятия и организации
    path('organization/', views.organization, name='organization'),
    path('organization/<slug:slug>/', views.organization_view, name='organization_view'),
    # С/х, лесное, рыболовство, рыбоводство
    path('shlrr/', views.shlrr, name='shlrr'),
    path('shlrr/<slug:slug>/', views.shlrr_view, name='shlrr_view'),
    # Информационные и коммуникационные технологии
    path('infotechnology/', views.infotechnology, name='infotechnology'),
    path('infotechnology/<slug:slug>/', views.infotechnology_view, name='infotechnology_view'),
    # Финансы
    path('finance/', views.finance, name='finance'),
    path('finance/<slug:slug>/', views.finance_view, name='finance_view'),
    # Внешняя торговля
    path('foreigntrading/', views.foreigntrading, name='foreigntrading'),
    path('foreigntrading/<slug:slug>/', views.foreigntrading_view, name='foreigntrading_view'),
    # Валовой региональный продукт
    path('vrp/', views.vrp, name='vrp'),
    path('vrp/<slug:slug>/', views.vrp_view, name='vrp_view'),
    # Промышленное производство
    path('industrialprod/', views.industrialprod, name='industrialprod'),
    path('industrialprod/<slug:slug>/', views.industrialprod_view, name='industrialprod_view'),

    # Модель
    path('download_model/<str:filename>/', views.download_model, name='download_model'),
]

situation_center/foresttrees/urls.py
from django.urls import path

from . import views


app_name = 'foresttrees'

urlpatterns = [
    # Здравоохранение
    path('hospital/', views.hospital, name='hospital'),
    path('hospital/<slug:slug>/', views.hospital_view, name='hospital_view'),
    # Образование
    path('study/', views.study, name='study'),
    path('study/<slug:slug>/', views.study_view, name='study_view'),
    # Демография
    path('demographics/', views.demographics, name='demographics'),
    path('demographics/<slug:slug>/', views.demographics_view, name='demographics_view'),
    # Культура
    path('culture/', views.culture, name='culture'),
    path('culture/<slug:slug>/', views.culture_view, name='culture_view'),
    # Дороги
    path('road/', views.road, name='road'),
    path('road/<slug:slug>/', views.road_view, name='road_view'),
    # Наука
    path('science/', views.science, name='science'),
    path('science/<slug:slug>/', views.science_view, name='science_view'),
    # Экология
    path('ecology/', views.ecology, name='ecology'),
    path('ecology/<slug:slug>/', views.ecology_view, name='ecology_view'),
    # Предпринимательство
    path('business/', views.business, name='business'),
    path('business/<slug:slug>/', views.business_view, name='business_view'),
    # Туризм
    path('turism/', views.turism, name='turism'),
    path('turism/<slug:slug>/', views.turism_view, name='turism_view'),
    # Жилье
    path('house/', views.house, name='house'),
    path('house/<slug:slug>/', views.house_view, name='house_view'),
    # Международная кооперация и экспорт
    path('world/', views.world, name='world'),
    path('world/<slug:slug>/', views.world_view, name='world_view'),
    # Труд
    path('labour/', views.labour, name='labour'),
    path('labour/<slug:slug>/', views.labour_view, name='labour_view'),
    # Атомка
    path('atom/', views.atom, name='atom'),
    path('atom/<slug:slug>/', views.atom_view, name='atom_view'),
    # Экономика
    path('econom/', views.econom, name='econom'),
    path('econom/<slug:slug>/', views.econom_view, name='econom_view'),
    # Магистральная
    path('mainline/', views.mainline, name='mainline'),
    path('mainline/<slug:slug>/', views.mainline_view, name='mainline_view'),
    # Промышленность
    path('industry/', views.industry, name='industry'),
    path('industry/<slug:slug>/', views.industry_view, name='industry_view'),
    # Сельское хозяйство
    path('agro/', views.agro, name='agro'),
    path('agro/<slug:slug>/', views.agro_view, name='agro_view'),
    # Строительство
    path('building/', views.building, name='building'),
    path('building/<slug:slug>/', views.building_view, name='building_view'),
    # Транспорт
    path('transport/', views.transport, name='transport'),
    path('transport/<slug:slug>/', views.transport_view, name='transport_view'),
    # Торговля
    path('trading/', views.trading, name='trading'),
    path('trading/<slug:slug>/', views.trading_view, name='trading_view'),
    # Услуги
    path('uslugi/', views.uslugi, name='uslugi'),
    path('uslugi/<slug:slug>/', views.uslugi_view, name='uslugi_view'),
    # Инвестиции
    path('investing/', views.investing, name='investing'),
    path('investing/<slug:slug>/', views.investing_view, name='investing_view'),
    # Финансы предприятий
    path('finpr/', views.finpr, name='finpr'),
    path('finpr/<slug:slug>/', views.finpr_view, name='finpr_view'),
    # Потребительские цены
    path('price/', views.price, name='price'),
    path('price/<slug:slug>/', views.price_view, name='price_view'),
    # Цены производителей
    path('prodprice/', views.prodprice, name='prodprice'),
    path('prodprice/<slug:slug>/', views.prodprice_view, name='prodprice_view'),
    # Доходы
    path('revenue/', views.revenue, name='revenue'),
    path('revenue/<slug:slug>/', views.revenue_view, name='revenue_view'),
    # Зарплата
    path('salary/', views.salary, name='salary'),
    path('salary/<slug:slug>/', views.salary_view, name='salary_view'),
    # Безработица
    path('joblessness/', views.joblessness, name='joblessness'),
    path('joblessness/<slug:slug>/', views.joblessness_view, name='joblessness_view'),
    # Рынок труда
    path('jobmarket/', views.jobmarket, name='jobmarket'),
    path('jobmarket/<slug:slug>/', views.jobmarket_view, name='jobmarket_view'),
    # Малые и средние предприятия
    path('smcompany/', views.smcompany, name='smcompany'),
    path('smcompany/<slug:slug>/', views.smcompany_view, name='smcompany_view'),
    # Население
    path('population/', views.population, name='population'),
    path('population/<slug:slug>/', views.population_view, name='population_view'),
    # Уровень жизни населения
    path('levelhealth/', views.levelhealth, name='levelhealth'),
    path('levelhealth/<slug:slug>/', views.levelhealth_view, name='levelhealth_view'),
    # Охрана природы
    path('securenature/', views.securenature, name='securenature'),
    path('securenature/<slug:slug>/', views.securenature_view, name='securenature_view'),
    # Основные фонды
    path('capitalassets/', views.capitalassets, name='capitalassets'),
    path('capitalassets/<slug:slug>/', views.capitalassets_view, name='capitalassets_view'),
    # Предприятия и организации
    path('organization/', views.organization, name='organization'),
    path('organization/<slug:slug>/', views.organization_view, name='organization_view'),
    # С/х, лесное, рыболовство, рыбоводство
    path('shlrr/', views.shlrr, name='shlrr'),
    path('shlrr/<slug:slug>/', views.shlrr_view, name='shlrr_view'),
    # Информационные и коммуникационные технологии
    path('infotechnology/', views.infotechnology, name='infotechnology'),
    path('infotechnology/<slug:slug>/', views.infotechnology_view, name='infotechnology_view'),
    # Финансы
    path('finance/', views.finance, name='finance'),
    path('finance/<slug:slug>/', views.finance_view, name='finance_view'),
    # Внешняя торговля
    path('foreigntrading/', views.foreigntrading, name='foreigntrading'),
    path('foreigntrading/<slug:slug>/', views.foreigntrading_view, name='foreigntrading_view'),
    # Валовой региональный продукт
    path('vrp/', views.vrp, name='vrp'),
    path('vrp/<slug:slug>/', views.vrp_view, name='vrp_view'),
    # Промышленное производство
    path('industrialprod/', views.industrialprod, name='industrialprod'),
    path('industrialprod/<slug:slug>/', views.industrialprod_view, name='industrialprod_view'),
]

situation_center/situation_center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from news.sitemaps import NewsSitemap

from django.conf import settings


handler400 = 'errors.views.tr_handler400'
handler403 = 'errors.views.tr_handler403'
handler404 = 'errors.views.tr_handler404'
handler429 = 'errors.views.tr_handler429'
handler500 = 'errors.views.tr_handler500'
handler503 = 'errors.views.tr_handler503'

sitemaps = {
    'posts': NewsSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('news.urls', namespace='news')),
    path('projects/', include('nathprojects.urls', namespace='nathprojects')),
    path('', include('errors.urls', namespace='errors')),
    path('', include('strategy.urls', namespace='strategy')),
    path('', include('userauth.urls', namespace='userauth')),
    path('api/', include('api.urls', namespace='api')),
    path('operdata/', include('operdata.urls', namespace='operdata')),
    path('yeardata/', include('yeardata.urls', namespace='yeardata')),
    path('rosstat/', include('rosstat.urls', namespace='rosstat')),
    path('foresttrees/', include('foresttrees.urls', namespace='foresttrees')),
    path('activeforecast/', include('activeforecast.urls', namespace='activeforecast')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('clustering/', include('clustering.urls', namespace='clustering')),

    # Карта сайта
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

situation_center/templates/foresttrees/capitalassets_result.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<section class="detailpr-section">
    <div class="container">

        <!-- Заголовок -->
        <div class="detailpr-section__title">Результаты для "{{ capitalassets.title }}"</div>

        <div class="detailpr-section__block">
            <p class="detailpr-section__description">Коэффициент детерминации на обучающей выборке: {{ train_r2_score }}</p>
            <p class="detailpr-section__description">Коэффициент детерминации на тестовой выборке: {{ test_r2_score }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на обучающей выборке: {{ train_mse }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на тестовой выборке: {{ test_mse }}</p>
        </div>

        <div class="detailpr-section__img">
            <h3>Значимость факторных переменных:</h3>
            <div>
                {{ feature_importances_plot|safe }}
            </div>
        </div>

        <div class="detailpr-section__wrapper">
            <h3 style="font-size: 20px; margin-bottom: 20px;">Деревья:</h3>
            <ul style="display: flex; flex-wrap: wrap;">
                {% for tree in trees %}
                    <li>
                        <button class="btn-tree" onclick="toggleTree({{ forloop.counter }})">{{ forloop.counter }}</button>
                        <pre id="tree{{ forloop.counter }}" style="display:none;">{{ tree|safe }}</pre>
                    </li>
                {% endfor %}
            </ul>
        </div>

</div>
</section>

<script>
    function toggleTree(id) {
        var x = document.getElementById("tree" + id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

{% endblock content %}

situation_center/templates/foresttrees/culture.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Культура</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for culture in cultures %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:culture_view' culture.slug %}" class="hospital-section__link">{{ culture.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/demographics_result.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<section class="detailpr-section">
    <div class="container">

        <!-- Заголовок -->
        <div class="detailpr-section__title">Результаты для "{{ demographics.title }}"</div>

        <div class="detailpr-section__block">
            <p class="detailpr-section__description">Коэффициент детерминации на обучающей выборке: {{ train_r2_score }}</p>
            <p class="detailpr-section__description">Коэффициент детерминации на тестовой выборке: {{ test_r2_score }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на обучающей выборке: {{ train_mse }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на тестовой выборке: {{ test_mse }}</p>
        </div>

        <div class="detailpr-section__img">
            <h3>Значимость факторных переменных:</h3>
            <div>
                {{ feature_importances_plot|safe }}
            </div>
        </div>

        <div class="detailpr-section__wrapper">
            <h3 style="font-size: 20px; margin-bottom: 20px;">Деревья:</h3>
            <ul style="display: flex; flex-wrap: wrap;">
                {% for tree in trees %}
                    <li>
                        <button class="btn-tree" onclick="toggleTree({{ forloop.counter }})">{{ forloop.counter }}</button>
                        <pre id="tree{{ forloop.counter }}" style="display:none;">{{ tree|safe }}</pre>
                    </li>
                {% endfor %}
            </ul>
        </div>

</div>
</section>

<script>
    function toggleTree(id) {
        var x = document.getElementById("tree" + id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

{% endblock content %}

situation_center/templates/foresttrees/ecology_result.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<section class="detailpr-section">
    <div class="container">

        <!-- Заголовок -->
        <div class="detailpr-section__title">Результаты для "{{ ecology.title }}"</div>

        <div class="detailpr-section__block">
            <p class="detailpr-section__description">Коэффициент детерминации на обучающей выборке: {{ train_r2_score }}</p>
            <p class="detailpr-section__description">Коэффициент детерминации на тестовой выборке: {{ test_r2_score }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на обучающей выборке: {{ train_mse }}</p>
            <p class="detailpr-section__description">Среднеквадратичная ошибка на тестовой выборке: {{ test_mse }}</p>
        </div>

        <div class="detailpr-section__img">
            <h3>Значимость факторных переменных:</h3>
            <div>
                {{ feature_importances_plot|safe }}
            </div>
        </div>

        <div class="detailpr-section__wrapper">
            <h3 style="font-size: 20px; margin-bottom: 20px;">Деревья:</h3>
            <ul style="display: flex; flex-wrap: wrap;">
                {% for tree in trees %}
                    <li>
                        <button class="btn-tree" onclick="toggleTree({{ forloop.counter }})">{{ forloop.counter }}</button>
                        <pre id="tree{{ forloop.counter }}" style="display:none;">{{ tree|safe }}</pre>
                    </li>
                {% endfor %}
            </ul>
        </div>

</div>
</section>

<script>
    function toggleTree(id) {
        var x = document.getElementById("tree" + id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

{% endblock content %}

situation_center/templates/foresttrees/finpr.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Финансы предприятий</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for finpr in finprs %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:finpr_view' finpr.slug %}" class="hospital-section__link">{{ finpr.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/levelhealth.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Уровень жизни населения</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for levelhealth in levelhealths %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:levelhealth_view' levelhealth.slug %}" class="hospital-section__link">{{ levelhealth.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/organization.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Предприятия и организации</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for organization in organizations %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:organization_view' organization.slug %}" class="hospital-section__link">{{ organization.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/road.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Безопасные дороги</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for road in roads %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:road_view' road.slug %}" class="hospital-section__link">{{ road.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/study.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Образование</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for study in studies %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:study_view' study.slug %}" class="hospital-section__link">{{ study.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/foresttrees/vrp.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ДЕРЕВЬЯ РЕГРЕССИИ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Валовой региональный продукт</h2>
        
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->
            <ol>
                {% for vrp in vrps %}
                <li style="list-style: auto; font-size: 30px; font-weight: 500;">
                    <div class="hospital-section__card">
                        <a href="{% url 'foresttrees:vrp_view' vrp.slug %}" class="hospital-section__link">{{ vrp.title }}</a>
                    </div>
                </li>
            {% endfor %}
            </ol>

        </div>

    </div>
</section>

{% endblock content %}