situation_center/ai/urls.py
from django.urls import path

from . import views


app_name = 'ai'

urlpatterns = [
    # Атомка
    path('atom/', views.atom, name='atom'),
    path('atom/<slug:slug>/', views.atom_view, name='atom_view'),
    # Здравоохранение
    path('hospital/', views.hospital, name='hospital'),
    path('hospital/<slug:slug>/', views.hospital_view, name='hospital_view'),
    # Образование
    path('study/', views.study, name='study'),
    path('study/<slug:slug>/', views.study_view, name='study_view'),
    # Демография
    path('demographics/', views.demographics, name='demographics'),
    path('demographics/<slug:slug>/', views.demographics_view, name='demographics_view'),
    # Культура
    path('culture/', views.culture, name='culture'),
    path('culture/<slug:slug>/', views.culture_view, name='culture_view'),
    # Дороги
    path('road/', views.road, name='road'),
    path('road/<slug:slug>/', views.road_view, name='road_view'),
    # Наука
    path('science/', views.science, name='science'),
    path('science/<slug:slug>/', views.science_view, name='science_view'),
    # Экология
    path('ecology/', views.ecology, name='ecology'),
    path('ecology/<slug:slug>/', views.ecology_view, name='ecology_view'),
    # Предпринимательство
    path('business/', views.business, name='business'),
    path('business/<slug:slug>/', views.business_view, name='business_view'),
    # Туризм
    path('turism/', views.turism, name='turism'),
    path('turism/<slug:slug>/', views.turism_view, name='turism_view'),
    # Жилье
    path('house/', views.house, name='house'),
    path('house/<slug:slug>/', views.house_view, name='house_view'),
    # Международная кооперация и экспорт
    path('world/', views.world, name='world'),
    path('world/<slug:slug>/', views.world_view, name='world_view'),
    # Труд
    path('labour/', views.labour, name='labour'),
    path('labour/<slug:slug>/', views.labour_view, name='labour_view'),
    # Экономика
    path('econom/', views.econom, name='econom'),
    path('econom/<slug:slug>/', views.econom_view, name='econom_view'),
    # Расширение магистральной инфраструктуры
    path('mainline/', views.mainline, name='mainline'),
    path('mainline/<slug:slug>/', views.mainline_view, name='mainline_view'),
    # Промышленность
    path('industry/', views.industry, name='industry'),
    path('industry/<slug:slug>/', views.industry_view, name='industry_view'),
    # Сельское хозяйство
    path('agro/', views.agro, name='agro'),
    path('agro/<slug:slug>/', views.agro_view, name='agro_view'),
    # Строительство
    path('building/', views.building, name='building'),
    path('building/<slug:slug>/', views.building_view, name='building_view'),
    # Транспорт
    path('transport/', views.transport, name='transport'),
    path('transport/<slug:slug>/', views.transport_view, name='transport_view'),
    # Торговля
    path('trading/', views.trading, name='trading'),
    path('trading/<slug:slug>/', views.trading_view, name='trading_view'),
    # Услуги
    path('uslugi/', views.uslugi, name='uslugi'),
    path('uslugi/<slug:slug>/', views.uslugi_view, name='uslugi_view'),
    # Инвестиции
    path('investing/', views.investing, name='investing'),
    path('investing/<slug:slug>/', views.investing_view, name='investing_view'),
    # Финансы предприятий
    path('finpr/', views.finpr, name='finpr'),
    path('finpr/<slug:slug>/', views.finpr_view, name='finpr_view'),
    # Потребительские цены
    path('price/', views.price, name='price'),
    path('price/<slug:slug>/', views.price_view, name='price_view'),
    # Цены производителей
    path('prodprice/', views.prodprice, name='prodprice'),
    path('prodprice/<slug:slug>/', views.prodprice_view, name='prodprice_view'),
    # Доходы
    path('revenue/', views.revenue, name='revenue'),
    path('revenue/<slug:slug>/', views.revenue_view, name='revenue_view'),
    # Зарплата
    path('salary/', views.salary, name='salary'),
    path('salary/<slug:slug>/', views.salary_view, name='salary_view'),
    # Безработица
    path('joblessness/', views.joblessness, name='joblessness'),
    path('joblessness/<slug:slug>/', views.joblessness_view, name='joblessness_view'),
    # Рынок труда
    path('jobmarket/', views.jobmarket, name='jobmarket'),
    path('jobmarket/<slug:slug>/', views.jobmarket_view, name='jobmarket_view'),
    # Малые и средние предприятия
    path('smcompany/', views.smcompany, name='smcompany'),
    path('smcompany/<slug:slug>/', views.smcompany_view, name='smcompany_view'),
    # Население
    path('population/', views.population, name='population'),
    path('population/<slug:slug>/', views.population_view, name='population_view'),
    # Уровень жизни населения
    path('levelhealth/', views.levelhealth, name='levelhealth'),
    path('levelhealth/<slug:slug>/', views.levelhealth_view, name='levelhealth_view'),
    # Охрана природы
    path('securenature/', views.securenature, name='securenature'),
    path('securenature/<slug:slug>/', views.securenature_view, name='securenature_view'),
    # Основные фонды
    path('capitalassets/', views.capitalassets, name='capitalassets'),
    path('capitalassets/<slug:slug>/', views.capitalassets_view, name='capitalassets_view'),
    # Предприятия и организации
    path('organization/', views.organization, name='organization'),
    path('organization/<slug:slug>/', views.organization_view, name='organization_view'),
    # С/х, лесное, рыболовство, рыбоводство
    path('shlrr/', views.shlrr, name='shlrr'),
    path('shlrr/<slug:slug>/', views.shlrr_view, name='shlrr_view'),
    # Информационные и коммуникационные технологии
    path('infotechnology/', views.infotechnology, name='infotechnology'),
    path('infotechnology/<slug:slug>/', views.infotechnology_view, name='infotechnology_view'),
    # Финансы
    path('finance/', views.finance, name='finance'),
    path('finance/<slug:slug>/', views.finance_view, name='finance_view'),
    # Внешняя торговля
    path('foreigntrading/', views.foreigntrading, name='foreigntrading'),
    path('foreigntrading/<slug:slug>/', views.foreigntrading_view, name='foreigntrading_view'),
    # Валовой региональный продукт
    path('vrp/', views.vrp, name='vrp'),
    path('vrp/<slug:slug>/', views.vrp_view, name='vrp_view'),
    # Промышленное производство
    path('industrialprod/', views.industrialprod, name='industrialprod'),
    path('industrialprod/<slug:slug>/', views.industrialprod_view, name='industrialprod_view'),

    # Модель
    path('download_model/<str:filename>/', views.download_model, name='download_model'),
]

situation_center/operdata/urls.py
from django.urls import path

from . import views


app_name = 'operdata'

urlpatterns = [
    # Промышленность
    path('operdata-industry/', views.industry, name='industry'),
    path('operdata-industry/<slug:slug>/', views.industry_detail, name='industry_detail'),
    # Сельское хозяйство
    path('operdata-agro/', views.agro, name='agro'),
    path('operdata-agro/<slug:slug>/', views.agro_detail, name='agro_detail'),
    # Строительство
    path('operdata-building/', views.building, name='building'),
    path('operdata-building/<slug:slug>/', views.building_detail, name='building_detail'),
    # Транспорт
    path('operdata-transport/', views.transport, name='transport'),
    path('operdata-transport/<slug:slug>/', views.transport_detail, name='transport_detail'),
    # Торговля
    path('operdata-trading/', views.trading, name='trading'),
    path('operdata-trading/<slug:slug>/', views.trading_detail, name='trading_detail'),
    # Услуги
    path('operdata-uslugi/', views.uslugi, name='uslugi'),
    path('operdata-uslugi/<slug:slug>/', views.uslugi_detail, name='uslugi_detail'),
    # Инвестиции
    path('operdata-investing/', views.investing, name='investing'),
    path('operdata-investing/<slug:slug>/', views.investing_detail, name='investing_detail'),
    # Финансы предприятий
    path('operdata-finpr/', views.finpr, name='finpr'),
    path('operdata-finpr/<slug:slug>/', views.finpr_detail, name='finpr_detail'),
    # Потребительские цены
    path('operdata-price/', views.price, name='price'),
    path('operdata-price/<slug:slug>/', views.price_detail, name='price_detail'),
    # Цены производителей
    path('operdata-prodprice/', views.prodprice, name='prodprice'),
    path('operdata-prodprice/<slug:slug>/', views.prodprice_detail, name='prodprice_detail'),
    # Доходы
    path('operdata-revenue/', views.revenue, name='revenue'),
    path('operdata-revenue/<slug:slug>/', views.revenue_detail, name='revenue_detail'),
    # Зарплата
    path('operdata-salary/', views.salary, name='salary'),
    path('operdata-salary/<slug:slug>/', views.salary_detail, name='salary_detail'),
    # Безработица
    path('operdata-joblessness/', views.joblessness, name='joblessness'),
    path('operdata-joblessness/<slug:slug>/', views.joblessness_detail, name='joblessness_detail'),
    # Рынок труда
    path('operdata-jobmarket/', views.jobmarket, name='jobmarket'),
    path('operdata-jobmarket/<slug:slug>/', views.jobmarket_detail, name='jobmarket_detail'),
    # Малые и средние предприятия
    path('operdata-smcompany/', views.smcompany, name='smcompany'),
    path('operdata-smcompany/<slug:slug>/', views.smcompany_detail, name='smcompany_detail'),
]

situation_center/situation_center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from news.sitemaps import NewsSitemap

from django.conf import settings


handler400 = 'errors.views.tr_handler400'
handler403 = 'errors.views.tr_handler403'
handler404 = 'errors.views.tr_handler404'
handler429 = 'errors.views.tr_handler429'
handler500 = 'errors.views.tr_handler500'
handler503 = 'errors.views.tr_handler503'

sitemaps = {
    'posts': NewsSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('news.urls', namespace='news')),
    path('projects/', include('nathprojects.urls', namespace='nathprojects')),
    path('', include('errors.urls', namespace='errors')),
    path('', include('strategy.urls', namespace='strategy')),
    path('', include('userauth.urls', namespace='userauth')),
    path('api/', include('api.urls', namespace='api')),
    path('operdata/', include('operdata.urls', namespace='operdata')),
    path('yeardata/', include('yeardata.urls', namespace='yeardata')),
    path('rosstat/', include('rosstat.urls', namespace='rosstat')),
    path('foresttrees/', include('foresttrees.urls', namespace='foresttrees')),
    path('activeforecast/', include('activeforecast.urls', namespace='activeforecast')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('clustering/', include('clustering.urls', namespace='clustering')),

    # Карта сайта
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

situation_center/templates/operdata/building_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ building.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'operdata:building_detail' slug=building.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ building.description }}</p>
            </div>

            
            {% comment %} <div>
                <h2>Круговая диаграмма</h2>
                <div>{{ pie_chart|safe }}</div>
            </div> {% endcomment %}
            <!-- Второй график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img2.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
            <!-- Третий график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img3.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/finpr.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ОПЕРАТИВНЫЕ ДАННЫЕ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Финансы предприятий</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере финансов предприятий. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты управления
            финансами предприятий, такие как динамика денежных потоков, распределение расходов и доходов,
            эффективность использования финансовых ресурсов и многое другое. Они помогают анализировать и понимать текущее
            состояние финансов предприятий в различных секторах или регионах, а также
            выявлять тенденции и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные финансовые показатели предприятий, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые финансовые показатели предприятий
            на одной панели управления. Они облегчают мониторинг текущей финансовой ситуации,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for finpr in finprs %}
            <div class="hospital-section__card">
                <a href="{% url 'operdata:finpr_detail' slug=finpr.slug %}" class="hospital-section__link">{{ finpr.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/industry.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ОПЕРАТИВНЫЕ ДАННЫЕ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Промышленность</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере промышленности. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты развития
            технологий в области промышленности, такие как динамика производства, распределение видов продукции,
            эффективность производственных процессов и многое другое. Они помогают анализировать и понимать текущее
            состояние промышленного сектора в различных регионах или странах, а также
            выявлять тенденции и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели промышленности, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели промышленности
            на одной панели управления. Они облегчают мониторинг текущей ситуации в промышленности,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for industry in industries %}
            <div class="hospital-section__card">
                <a href="{% url 'operdata:industry_detail' slug=industry.slug %}" class="hospital-section__link">{{ industry.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/industry_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ industry.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'operdata:industry_detail' slug=industry.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ industry.description }}</p>
            </div>

            
            {% comment %} <div>
                <h2>Круговая диаграмма</h2>
                <div>{{ pie_chart|safe }}</div>
            </div> {% endcomment %}
            <!-- Второй график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img2.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
            <!-- Третий график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img3.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/investing_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="detailpr-section">
    <div class="container">
        <!-- Заголовок -->
        <div class="detailpr-section__title">{{ investing.title }}</div>
        <!-- Обертка графиков -->
        <div class="detailpr-section__wrapper">
            <form class="custom-form-pr" method="get" action="{% url 'operdata:investing_detail' slug=investing.slug %}">
                <div class="form-group">
                    <select name="region" id="id_region">
                        {% for value, display in region_form.fields.region.choices %}
                            <option value="{{ value }}" {% if value == selected_region %}selected{% endif %}>
                                {{ display }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button class="custom-form-btn" type="submit">Фильтр</button>
            </form>
            <!-- Первый график -->
            {% comment %} <div id="chart" class="detailpr-section__img">{{ chart|safe }}</div> {% endcomment %}
            {% comment %} <div id="chart" class="detailpr-section__img">
                <h2>Линейный график</h2>
                <div>{{ line_chart|safe }}</div>
            </div>
            
            <div id="chart" class="detailpr-section__img">
                <h2>Столбчатая диаграмма</h2>
                <div>{{ bar_chart|safe }}</div>
            </div> {% endcomment %}
            {% if selected_region %}
                <h2>Выбранный регион: {{ selected_region }}</h2>
            {% endif %}
            <div id="chart" class="detailpr-section__img">
                <h2>Комбинированный график</h2>
                <div>{{ combined_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Логарифмическая шкала</h3>
                <div>{{ combined_chart_log|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Карта смертности</h3>
                <div>{{ map_chart_linear|safe }}</div>
            </div>
            <div id="chart" class="detailpr-section__img">
                <h3>Таблица данных</h3>
                <div>{{ table_html|safe }}</div>
            </div>
            <div class="detailpr-section__block">
                <p class="detailpr-section__description">{{ investing.description }}</p>
            </div>

            
            {% comment %} <div>
                <h2>Круговая диаграмма</h2>
                <div>{{ pie_chart|safe }}</div>
            </div> {% endcomment %}
            <!-- Второй график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img2.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
            <!-- Третий график -->
            {% comment %} <div class="detailpr-section__block">
                <img src="./assets/images/graph-img3.png" alt="график" class="detailpr-section__img">
                <p class="detailpr-section__description">Диаграмма аналитики по ТО то того</p>
            </div> {% endcomment %}
        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/joblessness.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ОПЕРАТИВНЫЕ ДАННЫЕ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Безработица</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере безработицы. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты динамики безработицы,
            такие как уровни безработицы, распределение безработных по возрастным и социальным группам,
            эффективность программ занятости и многое другое. Они помогают анализировать и понимать текущее
            состояние рынка труда в различных регионах или странах, а также
            выявлять тенденции и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели безработицы, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели безработицы
            на одной панели управления. Они облегчают мониторинг текущей ситуации на рынке труда,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for joblessness in joblessnesses %}
            <div class="hospital-section__card">
                <a href="{% url 'operdata:joblessness_detail' slug=joblessness.slug %}" class="hospital-section__link">{{ joblessness.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}

situation_center/templates/operdata/jobmarket.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<section class="hospital-section">
    <div class="container">
        <!-- Заголовок главный -->
        <h1 class="hospital-section__title">ОПЕРАТИВНЫЕ ДАННЫЕ</h1>
        <!-- Заголовок проекта -->
        <h2 class="hospital-section__title-project">Рынок труда</h2>
        <!-- Тексты -->
        <p class="hospital-section__text1">
            В данном разделе представлены аналитические отчеты, охватывающие широкий
            спектр данных в сфере рынка труда. Эти отчеты представлены в форме
            графиков, диаграмм и дашбордов, обеспечивая наглядное и информативное представление
            информации.
        </p>
        <p class="hospital-section__text2">
            Графики, представленные здесь, позволяют визуализировать различные аспекты динамики рынка труда,
            такие как уровень занятости, распределение вакансий по отраслям, эффективность программ обучения
            и переквалификации, а также многое другое. Они помогают анализировать и понимать текущее
            состояние рынка труда в различных регионах или странах, а также
            выявлять тенденции и прогнозировать возможные изменения.
        </p>
        <p class="hospital-section__text3">
            Диаграммы в отчетах предоставляют дополнительные инсайты, позволяя сравнивать
            различные показатели рынка труда, выявлять зависимости между различными переменными
            и идентифицировать ключевые факторы.
        </p>
        <p class="hospital-section__text4">
            Дашборды, в свою очередь, представляют собой комплексные инструменты аналитики,
            собирающие в себе различные графики, диаграммы и ключевые показатели рынка труда
            на одной панели управления. Они облегчают мониторинг текущей ситуации на рынке труда,
            а также помогают принимать информированные решения на основе актуальных данных.
        </p>
        <!-- Обертка проектов -->
        <div class="hospital-section__wrapper">
            <!-- Первый проект -->

            {% for jobmarket in jobmarkets %}
            <div class="hospital-section__card">
                <a href="{% url 'operdata:jobmarket_detail' slug=jobmarket.slug %}" class="hospital-section__link">{{ jobmarket.title }}</a>
            </div>
            {% endfor %}

        </div>

    </div>
</section>

{% endblock content %}